In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import IsolationForest
from sklearn.svm import OneClassSVM
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve, roc_auc_score,auc
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import f1_score

In [5]:
df = pd.read_csv("ICMP ATTACK DATASET.csv")
df.shape

(85063, 84)

In [6]:
df.columns

Index(['Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol',
       'Timestamp', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts',
       'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label'],
      dtype='object')

In [8]:
df.Label.value_counts()

Label
DDOS      65602
NORMAL    19460
Name: count, dtype: int64

Almost 3:1 DDOS to normal ratio. This is fine as later we can add normal traffic which is easier to generate.

In [ ]:
df = df.drop(columns = ['Timestamp','Flow ID','Src IP','Dst IP'])

In [10]:
df = df.dropna()

In [11]:
df.Label.value_counts()

Label
DDOS      65602
NORMAL    19443
Name: count, dtype: int64

In [15]:
le = LabelEncoder()
df['Label'] = le.fit_transform(df['Label'])
df.head()

,Src Port,Dst Port,Protocol,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,39168.0,443.0,6.0,10301270.0,5.0,7.0,517.0,4409.0,517.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,39170.0,443.0,6.0,13284978.0,5.0,7.0,517.0,4411.0,517.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,39170.0,443.0,6.0,169055.0,1.0,2.0,74.0,0.0,74.0,74.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,44264.0,53.0,17.0,63565.0,0.0,2.0,0.0,137.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,36943.0,443.0,17.0,1611997.0,13.0,19.0,5379.0,8967.0,1250.0,33.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [16]:
cormat = df.corr()
cormat = cormat.dropna(how = 'all', axis=1)
cormat = cormat.dropna(how = 'all', axis=0)
cormat.style.background_gradient(cmap='coolwarm')

In [22]:
cormat.shape

(66, 66)

In [17]:
def getCorrelationFeature(corrdata,threshold):
    feature=[]
    value=[]
    for i,index in enumerate(corrdata.index):
        if abs(corrdata[index])>threshold:
            feature.append(index)
            value.append(corrdata[index])
    df=pd.DataFrame(data=value,index=feature,columns=['corr values'])
    return df

In [26]:
threshold=0.50
corr_value=getCorrelationFeature(cormat['Label'],threshold)
corr_value

              corr values
Protocol         0.603098
Pkt Len Mean     0.545784
Pkt Len Std      0.501338
ACK Flag Cnt     0.526085
Pkt Size Avg     0.577708
Label            1.000000

In [27]:
len(corr_value)

6

Six features are too less let's adjust the threhold to 0.4 to so that we get atleast 15-20 features

In [28]:
threshold=0.40
corr_value=getCorrelationFeature(cormat['Label'],threshold)
corr_value

                  corr values
Protocol             0.603098
Bwd Pkt Len Max      0.475832
Bwd Pkt Len Min      0.405274
Bwd Pkt Len Mean     0.496963
Bwd Pkt Len Std      0.488018
Pkt Len Min          0.414263
Pkt Len Max          0.469885
Pkt Len Mean         0.545784
Pkt Len Std          0.501338
SYN Flag Cnt         0.419342
ACK Flag Cnt         0.526085
Pkt Size Avg         0.577708
Bwd Seg Size Avg     0.496963
Idle Mean            0.403424
Idle Max             0.409801
Label                1.000000

In [29]:
len(corr_value)

16

In [30]:
correlated_data=df[corr_value.index]
correlated_data.head()

,Protocol,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,SYN Flag Cnt,ACK Flag Cnt,Pkt Size Avg,Bwd Seg Size Avg,Idle Mean,Idle Max,Label
0,6.0,2860.0,0.0,629.857143,1121.166123,0.0,2860.0,378.923077,852.439388,1.0,0.0,410.500000,629.857143,0.0,0.0,0
1,6.0,1521.0,0.0,630.142857,786.382101,0.0,1521.0,379.076923,638.301060,1.0,0.0,410.666667,630.142857,0.0,0.0,0
2,6.0,0.0,0.0,0.000000,0.000000,0.0,74.0,18.500000,37.000000,0.0,1.0,24.666667,0.000000,0.0,0.0,0
3,17.0,93.0,44.0,68.500000,34.648232,44.0,93.0,60.333333,28.290163,0.0,0.0,90.500000,68.500000,0.0,0.0,0
4,17.0,1250.0,25.0,471.947368,526.736543,25.0,1250.0,472.606061,535.845298,0.0,0.0,487.375000,471.947368,0.0,0.0,0

In [31]:
x=correlated_data.drop(labels=['Label'],axis=1)
y=correlated_data['Label']
x.head()

,Protocol,Bwd Pkt Len Max,Bwd Pkt Len Min,Bwd Pkt Len Mean,Bwd Pkt Len Std,Pkt Len Min,Pkt Len Max,Pkt Len Mean,Pkt Len Std,SYN Flag Cnt,ACK Flag Cnt,Pkt Size Avg,Bwd Seg Size Avg,Idle Mean,Idle Max
0,6.0,2860.0,0.0,629.857143,1121.166123,0.0,2860.0,378.923077,852.439388,1.0,0.0,410.500000,629.857143,0.0,0.0
1,6.0,1521.0,0.0,630.142857,786.382101,0.0,1521.0,379.076923,638.301060,1.0,0.0,410.666667,630.142857,0.0,0.0
2,6.0,0.0,0.0,0.000000,0.000000,0.0,74.0,18.500000,37.000000,0.0,1.0,24.666667,0.000000,0.0,0.0
3,17.0,93.0,44.0,68.500000,34.648232,44.0,93.0,60.333333,28.290163,0.0,0.0,90.500000,68.500000,0.0,0.0
4,17.0,1250.0,25.0,471.947368,526.736543,25.0,1250.0,472.606061,535.845298,0.0,0.0,487.375000,471.947368,0.0,0.0

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=30)

In [33]:
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(68036, 15) (17009, 15)
(68036,) (17009,)

In [34]:
scaler = StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

print(x_test.shape)
print(x_train.shape)

(17009, 15)
(68036, 15)

In [52]:
y_train.value_counts()

Label
0    52459
1    15577
Name: count, dtype: int64

## Training Isolation Forest and OCSVM on normal data

In [53]:
X_train_normal = x_train[y_train == 1]

iso = IsolationForest(contamination=0.2, random_state=42)
iso.fit(X_train_normal)

y_pred_iso = iso.predict(x_test)

y_pred_iso = [0 if x == -1 else 1 for x in y_pred_iso]

In [54]:
ocsvm = OneClassSVM(kernel='rbf', nu=0.23, gamma='scale')

ocsvm.fit(X_train_normal)

y_pred_ocsvm = ocsvm.predict(x_test)

# Convert labels
y_pred_ocsvm = [0 if x == -1 else 1 for x in y_pred_ocsvm]

In [41]:
xgb = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    scale_pos_weight=3.3  # handle imbalance (~77:23)
)

xgb.fit(x_train, y_train)

y_pred_xgb = xgb.predict(x_test)

In [42]:
def evaluate_model(name, y_true, y_pred):
    print(f"\n{name}")
    print(confusion_matrix(y_true, y_pred))
    print(classification_report(y_true, y_pred))

In [55]:
evaluate_model("Isolation Forest", y_test, y_pred_iso)
evaluate_model("One-Class SVM", y_test, y_pred_ocsvm)
evaluate_model("XGBoost", y_test, y_pred_xgb)

Isolation Forest
[[    3 13140]
 [  831  3035]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00     13143
           1       0.19      0.79      0.30      3866

    accuracy                           0.18     17009
   macro avg       0.10      0.39      0.15     17009
weighted avg       0.05      0.18      0.07     17009


One-Class SVM
[[   13 13130]
 [ 1834  2032]]
              precision    recall  f1-score   support

           0       0.01      0.00      0.00     13143
           1       0.13      0.53      0.21      3866

    accuracy                           0.12     17009
   macro avg       0.07      0.26      0.11     17009
weighted avg       0.04      0.12      0.05     17009


XGBoost
[[13127    16]
 [    1  3865]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     13143
           1       1.00      1.00      1.00      3866

    accuracy                           1.00     17009
   macro avg       1.00      1.00      1.00     17009
weighted avg       1.00      1.00      1.00     17009

since the normal training data is pretty low one class SVM and Isolation forest model's struggled. Unsupervised might not be useful on this dataset